### ISSUE TITLE
OSX ARM (M1) support

### ISSUE THREAD

**Issue by stevenabreu7** [fabhertz95/expelliarmus#4]
Hi, thanks a lot for the library, I love the initiative. 

Is support for M1 chips planned? 

Cheers,
Steve

**Comment by biphasic** [comment]
Hey @stevenabreu7, we're using Github runners to compile the package on different machines, which currently doesn't include M1, but is in beta https://github.com/github/roadmap/issues/528 
As soon as it's available to us, we're definitely going to add it! Until then I unfortunately don't have an M1 machine at hand to test this. When you pip install expelliarmus, what is the stacktrace that you get currently?

**Comment by stevenabreu7** [comment]
Ah okay that's great then, thanks! Currently I just get 
```
ERROR: Could not find a version that satisfies the requirement expelliarmus (from versions: none)
ERROR: No matching distribution found for expelliarmus
```

**Comment by stevenabreu7** [comment]
Works, thanks! I added a pull request to add this to the README, feel free to merge or simply add it yourself whenever you feel fit. Cheers!

**Comment by biphasic** [comment]
great stuff!
